disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
  - type_body_length
  - file_length
  - function_body_length

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing

excluded:
  - .build
  - Package.swift

line_length:
  warning: 120
  error: 200

type_name:
  min_length: 2
